name: DevkitPPC Make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: pheenoh/devkitppc-gcn:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        #token: ${{secrets.PAT_MY_TOKEN}}
        submodules: recursive
    - name: Run Make
      run: make
